export const GIFT_MODELS = [
  "Delicious Cake",
  "Green Star",
  "Blue Star",
  "Red Star",
  "Tropical Paradise",
  "Pink Heart",
  "Winter Magic",
  "Golden Crown",
  "Ruby Heart",
  "Emerald Tree",
] as const;

export const GIFT_BACKGROUNDS = [
  "Pattern 1",
  "Pattern 2",
  "Pattern 3",
  "Pattern 4",
  "Pattern 5",
  "Pattern 6",
  "Pattern 7",
  "Pattern 8",
  "Pattern 9",
  "Pattern 10",
] as const;

export type GiftModel = typeof GIFT_MODELS[number];
export type GiftBackground = typeof GIFT_BACKGROUNDS[number];

export const AVAILABLE_GIFTS = [
  { id: "1-may", name: "1 May", image: "/gifts/1 May.jpg", model: "Red Star" as GiftModel, background: "Pattern 1" as GiftBackground },
  { id: "8-march-cake", name: "8 March Cake", image: "/gifts/8 March Cake.jpg", model: "Delicious Cake" as GiftModel, background: "Pattern 2" as GiftBackground },
  { id: "8-march-rose", name: "8 march rose", image: "/gifts/8 march rose.jpg", model: "Pink Heart" as GiftModel, background: "Pattern 3" as GiftBackground },
  { id: "box-of-chocolates", name: "Box of chocolates", image: "/gifts/Box of chocolates.jpg", model: "Delicious Cake" as GiftModel, background: "Pattern 1" as GiftBackground },
  { id: "candle-lamp", name: "Candle lamp", image: "/gifts/Candle lamp.jpg", model: "Winter Magic" as GiftModel, background: "Pattern 4" as GiftBackground },
  { id: "cherry-cake", name: "Cherry cake", image: "/gifts/Cherry cake.jpg", model: "Delicious Cake" as GiftModel, background: "Pattern 2" as GiftBackground },
  { id: "coconut", name: "Coconut", image: "/gifts/Coconut.jpg", model: "Tropical Paradise" as GiftModel, background: "Pattern 5" as GiftBackground },
  { id: "crescent-moon", name: "Crescent Moon", image: "/gifts/Crescent Moon.jpg", model: "Winter Magic" as GiftModel, background: "Pattern 6" as GiftBackground },
  { id: "crystal-eagle", name: "Crystal eagle", image: "/gifts/Crystal eagle.jpg", model: "Golden Crown" as GiftModel, background: "Pattern 7" as GiftBackground },
  { id: "easter-basket", name: "Easter basket", image: "/gifts/Easter basket.jpg", model: "Tropical Paradise" as GiftModel, background: "Pattern 3" as GiftBackground },
  { id: "easter-cake", name: "Easter cake", image: "/gifts/Easter cake.jpg", model: "Delicious Cake" as GiftModel, background: "Pattern 8" as GiftBackground },
  { id: "gift-bag", name: "Gift Bag", image: "/gifts/Gift Bag.jpg", model: "Pink Heart" as GiftModel, background: "Pattern 1" as GiftBackground },
  { id: "gold-nipples", name: "Gold Nipples", image: "/gifts/Gold Nipples.jpg", model: "Golden Crown" as GiftModel, background: "Pattern 9" as GiftBackground },
  { id: "heels", name: "Heels", image: "/gifts/Heels.jpg", model: "Ruby Heart" as GiftModel, background: "Pattern 2" as GiftBackground },
  { id: "ice-cream-bar", name: "Ice cream bar", image: "/gifts/Ice cream bar.jpg", model: "Tropical Paradise" as GiftModel, background: "Pattern 5" as GiftBackground },
  { id: "ice-cream-cone", name: "Ice cream cone", image: "/gifts/Ice cream cone.jpg", model: "Tropical Paradise" as GiftModel, background: "Pattern 6" as GiftBackground },
  { id: "ice-cream-scoops", name: "Ice cream scoops", image: "/gifts/Ice cream scoops.jpg", model: "Tropical Paradise" as GiftModel, background: "Pattern 4" as GiftBackground },
  { id: "instant-noodles", name: "Instant noodles", image: "/gifts/Instant noodles.jpg", model: "Delicious Cake" as GiftModel, background: "Pattern 3" as GiftBackground },
  { id: "leperchaun-pot", name: "Leperchaun pot", image: "/gifts/Leperchaun pot.jpg", model: "Emerald Tree" as GiftModel, background: "Pattern 7" as GiftBackground },
  { id: "medal", name: "Medal", image: "/gifts/Medal.jpg", model: "Golden Crown" as GiftModel, background: "Pattern 10" as GiftBackground },
  { id: "money-bouquet", name: "Money bouquet", image: "/gifts/Money bouquet.jpg", model: "Emerald Tree" as GiftModel, background: "Pattern 8" as GiftBackground },
  { id: "mosque", name: "Mosque", image: "/gifts/Mosque.jpg", model: "Golden Crown" as GiftModel, background: "Pattern 9" as GiftBackground },
  { id: "peace-dove", name: "Peace dove", image: "/gifts/Peace dove.jpg", model: "Winter Magic" as GiftModel, background: "Pattern 1" as GiftBackground },
  { id: "pink-flamingo", name: "Pink Flamingo", image: "/gifts/Pink Flamingo.jpg", model: "Pink Heart" as GiftModel, background: "Pattern 5" as GiftBackground },
  { id: "poop", name: "Poop", image: "/gifts/Poop.jpg", model: "Delicious Cake" as GiftModel, background: "Pattern 2" as GiftBackground },
  { id: "red-star", name: "Red star", image: "/gifts/Red star.jpg", model: "Red Star" as GiftModel, background: "Pattern 3" as GiftBackground },
  { id: "sandcastle", name: "Sandcastle", image: "/gifts/Sandcastle.jpg", model: "Tropical Paradise" as GiftModel, background: "Pattern 4" as GiftBackground },
  { id: "statue-of-liberty", name: "Statue of liberty", image: "/gifts/Statue of liberty.jpg", model: "Blue Star" as GiftModel, background: "Pattern 6" as GiftBackground },
  { id: "surfboard", name: "Surfboard", image: "/gifts/Surfboard.jpg", model: "Tropical Paradise" as GiftModel, background: "Pattern 7" as GiftBackground },
  { id: "torch-of-freedom", name: "Torch of freedom", image: "/gifts/Torch of freedom.jpg", model: "Golden Crown" as GiftModel, background: "Pattern 8" as GiftBackground },
];
