export const AVAILABLE_GIFTS = [
  { id: "1-may", name: "1 May", image: "/gifts/1 May.jpg" },
  { id: "8-march-cake", name: "8 March Cake", image: "/gifts/8 March Cake.jpg" },
  { id: "8-march-rose", name: "8 march rose", image: "/gifts/8 march rose.jpg" },
  { id: "box-of-chocolates", name: "Box of chocolates", image: "/gifts/Box of chocolates.jpg" },
  { id: "candle-lamp", name: "Candle lamp", image: "/gifts/Candle lamp.jpg" },
  { id: "cherry-cake", name: "Cherry cake", image: "/gifts/Cherry cake.jpg" },
  { id: "coconut", name: "Coconut", image: "/gifts/Coconut.jpg" },
  { id: "crescent-moon", name: "Crescent Moon", image: "/gifts/Crescent Moon.jpg" },
  { id: "crystal-eagle", name: "Crystal eagle", image: "/gifts/Crystal eagle.jpg" },
  { id: "easter-basket", name: "Easter basket", image: "/gifts/Easter basket.jpg" },
  { id: "easter-cake", name: "Easter cake", image: "/gifts/Easter cake.jpg" },
  { id: "gift-bag", name: "Gift Bag", image: "/gifts/Gift Bag.jpg" },
  { id: "gold-nipples", name: "Gold Nipples", image: "/gifts/Gold Nipples.jpg" },
  { id: "heels", name: "Heels", image: "/gifts/Heels.jpg" },
  { id: "ice-cream-bar", name: "Ice cream bar", image: "/gifts/Ice cream bar.jpg" },
  { id: "ice-cream-cone", name: "Ice cream cone", image: "/gifts/Ice cream cone.jpg" },
  { id: "ice-cream-scoops", name: "Ice cream scoops", image: "/gifts/Ice cream scoops.jpg" },
  { id: "instant-noodles", name: "Instant noodles", image: "/gifts/Instant noodles.jpg" },
  { id: "leperchaun-pot", name: "Leperchaun pot", image: "/gifts/Leperchaun pot.jpg" },
  { id: "medal", name: "Medal", image: "/gifts/Medal.jpg" },
  { id: "money-bouquet", name: "Money bouquet", image: "/gifts/Money bouquet.jpg" },
  { id: "mosque", name: "Mosque", image: "/gifts/Mosque.jpg" },
  { id: "peace-dove", name: "Peace dove", image: "/gifts/Peace dove.jpg" },
  { id: "pink-flamingo", name: "Pink Flamingo", image: "/gifts/Pink Flamingo.jpg" },
  { id: "poop", name: "Poop", image: "/gifts/Poop.jpg" },
  { id: "red-star", name: "Red star", image: "/gifts/Red star.jpg" },
  { id: "sandcastle", name: "Sandcastle", image: "/gifts/Sandcastle.jpg" },
  { id: "statue-of-liberty", name: "Statue of liberty", image: "/gifts/Statue of liberty.jpg" },
  { id: "surfboard", name: "Surfboard", image: "/gifts/Surfboard.jpg" },
  { id: "torch-of-freedom", name: "Torch of freedom", image: "/gifts/Torch of freedom.jpg" },
];
